version: "3"
services:
  client:
    image: "partical1/partical_client:1.0.1"
    restart: always
    volumes:
      - /srv/app/prisma
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
